import { Inter } from "next/font/google";
import "./globals.css";


import "react-toastify/dist/ReactToastify.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "../../services/AuthProvider";
import { ToastContainer } from "react-toastify";



// import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className bg-white`}>
        <ToastContainer />
        <AuthProvider>
          <Navbar />

          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
